// Generated by ts-to-zod
import { z } from "zod";

export const addTodoRequestSchema = z.object({
  content: z.string(),
  status: z.boolean(),
});

export const addTodoResponseSchema = z.object({
  id: z.string(),
});
