import express, { Application } from "express";
import { Command } from "commander";
import { Router } from "./router";
import { generateSCConfigFile } from "./config";

export interface ServerConfig {
  name: string;
  port?: number;
  baseUrl?: string;
}

export class Server {
  private config: ServerConfig;
  private app: express.Application;
  private routerObj: Router;
  private program: Command;

  public constructor(config: ServerConfig) {

    // Initialise the server object
    this.config = config;

    // Set default values if not provided
    if (!this.config.baseUrl) this.config.baseUrl = "/v1";
    if (!this.config.port) this.config.port = 3000;

    // Create a router object
    this.routerObj = new Router({ name: this.config.name, baseUrl: this.config.baseUrl });

    // Create an express app
    this.app = express();

    // Create an a commander object
    this.program = new Command();
    this.program
      .name(this.config.name)
      .description(`"${this.config.name}" is a SpaceCloud worker`);

    this.program.option("--save-openapi", "Save the autogenerated OpenAPI configuration", false);
    this.program.option("-f, --file <path>", "File path to store the configuration.", ".");
  }

  /**
   * Create returns a new instance of the server object
   * @param config Object to configure server properties
   * @returns A `Server` object
   */
  public static create(config: ServerConfig): Server {
    return new Server(config);
  }

  /**
   * Router returns a router object to register your operations
   * @returns Router object
   */
  public router(): Router {
    return this.routerObj;
  }

  public getExpressApp(): Application {
    return this.app;
  }

  /**
   * Start begins the server operation. It will start an http server on the specified port.
   * It also exposes the OpenAPI spec for this server on `${baseUrl}/openapi.json`.
   */
  public start() {
    // Generate the open api spec for the app
    this.routerObj._generateOpenApi();

    // Parse the commands passed
    this.program.parse();
    const options = this.program.opts();

    // Check if the `--save-openapi` flag has been provided
    if (options["saveOpenapi"]) {
      const path = `${options["file"]}/openapi.yaml`;
      console.log(`Generating OpenAPI file at path - "${path}"`);
      generateSCConfigFile(path, this.routerObj._getOpenApiSpec());
      console.log("Open API configuration has been successfully saved!");
      return;
    }

    // Then add the global middlewares we need
    this.app.use(express.json());

    // Add a default route
    this.app.get("/info", (req, res) => {
      res.json({ name: this.config.name });
    });

    // Add the routes to the express app
    this.routerObj._initialiseRoutes(this.app);

    this.app.listen(this.config.port, () => {
      console.log(`⚡️[server]: Server is running at http://localhost:${this.config.port}`);
    });
  }
}
